### ISSUE TITLE
Share this strategy with "hossein"

### ISSUE THREAD

**Issue by BamdadTabari** [Dayana-World/Dayana-Web-v1-failed-#89]
hi @HosseinChoopani  what type of shit do you prefer me to eat for LinkedIn posts and docs and articles and more and more

**Comment by HosseinChoopani** [comment]
I have kind of never been into Linkedin. I should see some programming groups on Linkedin and figure out what's going on there.
I will tell you in these days.

**Comment by MohammadJavadTabari** [comment]
> I have kind of never been into Linkedin. I should see some programming groups on Linkedin and figure out what's going on there. I will tell you in these days.

if you have not any time it's ok,  i will do it myself

**Comment by HosseinChoopani** [comment]
I did a little research. told you the results in the telegram. if I came up with new ideas, will tell you.

**Comment by BamdadTabari** [comment]
that's ok,  thanks man
